version: "3.7"
services:
    api:
      build: .
      command: npm run start
      volumes: 
        - './opt/api'
      ports:
        - '5000:5000'
    mongo:
      image: 'mongo:4'
      environment: 
        - MONGO_INITDB_DATABASE=test
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      volumes:
        - ./mongo-volume:/data/db
      ports:
        - '27017:27017'
      